name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
#     - name: WakaTime Coding Statistics
#       uses: tariksahni/coding-stats-wakatime@v1.0.1
#       with:
#         # WakaTime API Key
#         WAKATIME_API_KEY: 
#         # Github token of the repo for the authentication
#        REPO_TOKEN: 
#     - name: SQLCheck Action
#       uses: yokawasa/action-sqlcheck@v1.3.0
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.4
      with:
        # The version to install
        rust-version:  1.49.0 
#     - name: Build
#       run: cd cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
